### ISSUE TITLE
support for more than 15 tags per each resource

### ISSUE THREAD

**Issue by cppforlife** [cloudfoundry/bosh-azure-cpi-release#383]
it appears that azure arm limits users to 15 tags per each resource. it would be nice to have ability to set more tags per resource so that adding customer provided tags (eg: `business unit`) do not have to compete with generic bosh tags (`deployment`, `director`, etc.). it seems that ~50 is a magic number for other IaaSes.

on a related subject, it appears that cpi always sets `user-agent` tag and sometimes adds number of `disk-id-bosh-disk-*` depending on number of attached disks. can azure cpi eliminate use of tags for its own purposes?

**Comment by gossion** [comment]
Hi @cppforlife ,

According to [azure document](https://docs.microsoft.com/en-us/azure/azure-resource-manager/resource-group-using-tags), it is true that each resource can have up to 15 tags, and it also has recommendation that `If you have more than 15 values that you need to associate with a resource, use a JSON string for the tag value. The JSON string can contain many values that are applied to a single tag name. ` 

To solve the limitation, we can change behavior of API `set_vm_metadata` to merge tags into one or several tags (the tag value is limited to 256 characters, so we may need more than 1 tag). so the possible new tags can be like this:
```json
      "tags": {
        "bosh-tags-0": "{\"deployment\":\"xxx\",\"jobs\":\"xxx...\"}",
        "bosh-tags-1": "{\"instance_group\":\"xxx\",\"index\":\"xxx...\"}"
      },
```

how do you think about this change?

**Comment by cppforlife** [comment]
> To solve the limitation, we can change behavior of API set_vm_metadata to merge tags into one or several tags

@gossion i dont think it would be very user friendly for filtering and seeing in ui. these fields are mostly there for humans.

> on a related subject, it appears that cpi always sets user-agent tag and sometimes adds number of disk-id-bosh-disk-* depending on number of attached disks. can azure cpi eliminate use of tags for its own purposes?

do you have any thoughts on the following?

**Comment by gossion** [comment]
Hi @cppforlife ,

"user-agent" tag is the tag to identified that the resources were created by bosh, currently we use this tag to summarize how many VMs are created by bosh cpi.

"disk-id-bosh-disk-*" is the tag to map disk name to a disk cid, for example: 
a tag `disk-id-bosh-disk-data-cae0e09f-ccff-4615-a8e3-a1c7f8f00fb3 : caching:None;disk_name:bosh-disk-data-cae0e09f-ccff-4615-a8e3-a1c7f8f00fb3;resource_group_name:my-rg-name` means that the VM has a disk  `disk-id-bosh-disk-data-cae0e09f-ccff-4615-a8e3-a1c7f8f00fb3` attached to it, and the cid of the disk is `caching:None;disk_name:bosh-disk-data-cae0e09f-ccff-4615-a8e3-a1c7f8f00fb3;resource_group_name:my-rg-name`. This tag is used in CPI API [get_disks](https://bosh.io/docs/cpi-api-v1/#get-disks), see its code [here](https://github.com/cloudfoundry-incubator/bosh-azure-cpi-release/blob/v35.2.0/src/bosh_azure_cpi/lib/cloud/azure/cloud.rb#L570). The tag is added when a persistent disk is attached to a VM, and removed when the persistent disk is detached. Currently there is not a good way to remove this tag, because disk cid is not a real id on Azure.

**Comment by cppforlife** [comment]
> "user-agent" tag is the tag to identified that the resources were created by bosh, currently we use this tag to summarize how many VMs are created by bosh cpi.

given that it's already easy enough to identify bosh vms via director/deployment/etc. tags i dont see a reason to waste extra tag on it.

> This tag is used in CPI API get_disks, see its code here.

could we be tagging persistent disk itself, and get_disks would just iterate over attached disks and then look at their tags?

**Comment by cppforlife** [comment]
> are 14 tags enough for sure

well if you count bosh tags (provided by the director) customer is only left with ~5. in their case it wasnt enough, so they just decided to override certain tags. i've indicated to them that it's not ok to override disk-id-* but user-agent is ok.

**Comment by gossion** [comment]
I got an answer from Azure team that they are working on increasing tags limit, however, there is no EAT yet. Will update once I get the ETA.

**Comment by cppforlife** [comment]
@gossion nice! do you know what they will be increasing it to?

**Comment by gossion** [comment]
Just checked, no info yet. I will get you updated later.

**Comment by h4xnoodle** [comment]
Closing this issue, assuming it has been resolved now. Thank you.
