### ISSUE TITLE
Permissions issue if more then one user doing deployments

### ISSUE THREAD

**Issue by gawlikpa** [cloudfoundry/bosh-azure-cpi-release#640]
### Versions (*please add them if you have more releases for this issue*)
CPI      37.6.0
BOSH     Version: 6.4.6-51f35e62-2021-09-07T19:05:01Z

### Stemcell
Version: ubuntu-bionic/1.25
Distro:
  - [x] Ubuntu
  - [ ] CentOS

### Environment
- Azure Environment:
  - [ ] Azure

### Issue Details

Starting with version 37.6.0 the cpi creates a folder under /tmp called azure_cpi which has its permissions set by the user that first runs a deployment with the new cpi, in the folder a lock file is created.  The issue is if a second user tries to run a deploy they will get a permissions denied error due to the above folder being accessible only by the first user. Additionally the lock files are not cleaned up after a successful deployment.

Also in the /tmp folder is a file called 'azure_cpi_telemetry.log' that also has restricted permissions that will prevent other users from deploying to azure via the azure cpi

**Comment by gawlikpa** [comment]
it only occurs when we are running the update for the bosh director, and only since the latest cpi version. The first part of the error is below:

Deploying:
  Creating instance 'bosh/0':
    Creating VM:
      Creating vm with stemcell cid 'bosh-stemcell-90b3a765-156b-4135-b87a-8c57a93a1820':
        CPI 'create_vm' method responded with error: CmdError{"type":"Bosh::Clouds::VMCreationFailed","message":"#\u003cBosh::Clouds::VMCreationFailed: Failed to get the user image information for the stemcell 'bosh-stemcell-90b3a765-156b-4135-b87a-8c57a93a1820': #\u003cErrno::EACCES: Permission denied @ rb_sysopen - /tmp/azure_cpi/bosh-lock-create-user-image-90b3a765-156b-4135-b87a-8c57a93a1820-S-canadacentral

Also to be clear there are multiple admins that use a common jumpbox, but only one admin is running the bosh director update at a time. So when user01 ran the create_vm it created a folder called /tmp/, as well as the /tmp/azure_cpi_telemetry.log file, with user01 as the sole owner. 

if any other user tries to update the bosh director they ran into the issue above due to both the folder and file being accessible to user01 only. This is only resolved when the folder and file permissions are manually changed to allow any user to access them

**Comment by klakin-pivotal** [comment]
Thanks much for the report!

Given that the majority (maybe all?) of our customers interact with their Directors through CI, which typically (always?) uses a single user to interact with their Directors... so fixing this isn't something that our team will get around to in any reasonable amount of time.

If your analysis is correct, _hopefully_ it'll be relatively easy to fix the permissions on the directory that Bosh creates, and -assuming that this doesn't create any security issues because the permissions of subdirectories in this directory are too permissive-, this should be a pretty easy PR for you folks to create.

If you've the interest, we'd be quite happy to evaluate and merge a good PR.

**Comment by bgandon** [comment]
Trying to jump in and start thinking of a solution.

At first thought I would think the CPI has to use its own ephemeral disk space in `/var/vcap/data/<job-name>` instead of `/tmp`. But where is that space when running `bosh create-env`? Probably under `~/.bosh`, but then how would the CPI job know about the exact location of the directory to use? So far I haven't seen any CPI config for the directory to use for ephemeral disk space. When we find answers to those questions, then we should document it for future CPI authors and maintainers.

Maybe worth to mention, `/tmp` is supposed to be limited to 128MB on BOSH instances, which is not relevant to unpack a Stemcell (roughly ≈3GB unpacked if I remember correctly). See: https://bosh.io/docs/vm-config/#global

There are several places of the Azure CPI code where `/tmp` is used currently:
- In `StemcellManager`: https://github.com/cloudfoundry/bosh-azure-cpi-release/blob/ca6886a8b43ffbe56a44b594ec2a73af745ab77d/src/bosh_azure_cpi/lib/cloud/azure/stemcell/stemcell_manager.rb#L41-L44
- in `Helpers.CPI_LOCK_DIR`: https://github.com/cloudfoundry/bosh-azure-cpi-release/blob/f10d573a5e6dbdbb22e90022ec4ceaeb0566b77b/src/bosh_azure_cpi/lib/cloud/azure/utils/helpers.rb#L137
- in `Helpers.CPI_EVENTS_DIR` : https://github.com/cloudfoundry/bosh-azure-cpi-release/blob/f10d573a5e6dbdbb22e90022ec4ceaeb0566b77b/src/bosh_azure_cpi/lib/cloud/azure/utils/helpers.rb#L175
- in `TelemetryManager`: https://github.com/cloudfoundry/bosh-azure-cpi-release/blob/ca6886a8b43ffbe56a44b594ec2a73af745ab77d/src/bosh_azure_cpi/lib/cloud/azure/telemetry/telemetry_manager.rb#L78

How do the other CPIs tackle this challenge?
Is this only a matter of making sure that the created bits are properly cleaned up on any CPI exit?

Anyway this is a good catch, and probable a nice learning for CPI design.
